apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: europe-west2-docker.pkg.dev/k8s-enablement-0e0eb5f6/nginx-demo/nginx:2.<ID>
        ports:
        - containerPort: 80
